-- ==========================================================
-- TMS SAMPLE DATA INSERT SCRIPT (Logical Data Flow)
-- ==========================================================

-- 1. COACH CENTER
INSERT INTO MSTR_COACH_CENTER (MC_CENTER_ID, MIC_CENTER_NM, MIC_CENTER_ADDRESS, MIC_CENTER_CITY, MIC_CENTER_STATE, MIC_CENTER_PIN, MIC_CENTER_COUNTRY, MIC_CENTER_EMAILID, MIC_CENTER_CONTACTNO)
VALUES ('CC001', 'Aimtech Education', 'A-12 Sector 63', 'Noida', 'UP', 201301, 'India', 'info@aimtech.com', '9876543210');

-- 2. BRANCH (Depends on Coach Center)
INSERT INTO CC_BRANCH (CC_BR_ID, CC_BR_CENTER_ID, CC_BR_NM, CC_BR_ADDRESS, CC_BR_CITY, CC_BR_STATE, CC_BR_PIN, CC_BR_COUNTRY, CC_BR_EMAILID, CC_BR_CONTACTNO)
VALUES ('BR001', 'CC001', 'Noida Main Branch', 'B-45 Sector 15', 'Noida', 'UP', 201301, 'India', 'noida@aimtech.com', '1234567890');

-- 3. TEACHER
INSERT INTO MSTR_TEACHER (TCHR_ID, TCHR_NM, TCHR_AADHAR, TCHR_PANCARD, TCHR_EMAILID, TCHR_CONTACTNO, TCHR_ADDRESS, TCHR_CITY, TCHR_STATE, TCHR_PIN, TCHR_COUNTRY)
VALUES ('T001', 'Dr. Rajesh Kumar', '123456789012', 'ABCDE1234F', 'rajesh@example.com', '9988776655', 'Professor Colony', 'Noida', 'UP', 201301, 'India');

-- 4. PARENT
INSERT INTO MSTR_PRNT (PRNT_ID, PRNT_NM, PRNT_AADHAR, PRNT_EMAILID, PRNT_CONTACTNO, PRNT_ADDRESS, PRNT_CITY, PRNT_STATE, PRNT_PIN, PRNT_COUNTRY)
VALUES ('P001', 'Mr. Suresh Sharma', '987654321098', 'suresh@example.com', '8877665544', 'Green Park', 'Noida', 'UP', 201301, 'India');

-- 5. STUDENT (Depends on Parent)
INSERT INTO MSTR_STU (STU_ID, STU_NM, STU_AADHAR, STU_EMAILID, STU_CONTACTNO, STU_ADDRESS, STU_CITY, STU_STATE, STU_PIN, STU_COUNTRY, STU_DOB, STU_PRNT_ID)
VALUES ('S001', 'Amit Sharma', '456789012345', 'amit@student.com', '7766554433', 'Green Park', 'Noida', 'UP', 201301, 'India', '2010-08-15', 'P001');

-- 6. SUBJECT
INSERT INTO MSTR_SUB (SUB_ID, SUB_NAME, SUB_BOARD, SUB_CLASS, SUB_LANG)
VALUES ('SUB001', 'Mathematics', 'CBSE', '10th', 'English'),
       ('SUB002', 'Science', 'CBSE', '10th', 'English');

-- 7. TEACHER-SUBJECT MAP (Depends on Teacher, Subject, Branch)
INSERT INTO MAP_TCHR_SUB (MTS_ID, MTS_TCHR_ID, MTS_SUB, MTS_BR_ID)
VALUES ('MTS001', 'T001', 'SUB001', 'BR001');

-- 8. STUDENT-SUBJECT MAP (Depends on Student, Teacher-Subject Map)
INSERT INTO MAP_STU_SUB (MSS_ID, MSS_STU_ID, MSS_STU_TCHR, MSS_STU_DOW, MSS_STU_TIME)
VALUES ('MSS001', 'S001', 'MTS001', 'Mon-Wed', '10:00 AM');
